import React from 'react';
import { 
  Users, 
  LayoutDashboard, 
  ShoppingBasket, 
  BarChart2, 
  Settings, 
  ChevronDown, 
  PlusCircle, 
  Edit, 
  Trash2, 
  QrCode, 
  LogIn, 
  LogOut, 
  Sun, 
  Moon, 
  Sparkles,
  Home,
  DollarSign,
  FileText,
  Building,
  ExternalLink,
  Upload,
  ShoppingCart,
  Plus,
  Minus,
  X,
  Link,
  Check,
  BookOpen,
  CreditCard,
  Loader2,
  Store,
  Printer,
  MessageSquare,
  Smartphone,
  ScanLine,
  Warehouse,
  Receipt,
  Smile,
  GitMerge,
  Cloud,
  Cog,
  Star,
} from 'lucide-react';

type IconProps = { className?: string };

export const Icons = {
  Dashboard: (props: IconProps) => <LayoutDashboard {...props} />,
  Branches: (props: IconProps) => <Building {...props} />,
  Menu: (props: IconProps) => <FileText {...props} />,
  Reports: (props: IconProps) => <BarChart2 {...props} />,
  Settings: (props: IconProps) => <Settings {...props} />,
  Add: (props: IconProps) => <PlusCircle {...props} />,
  Edit: (props: IconProps) => <Edit {...props} />,
  Delete: (props: IconProps) => <Trash2 {...props} />,
  QRCode: (props: IconProps) => <QrCode {...props} />,
  Login: (props: IconProps) => <LogIn {...props} />,
  Logout: (props: IconProps) => <LogOut {...props} />,
  Sun: (props: IconProps) => <Sun {...props} />,
  Moon: (props: IconProps) => <Moon {...props} />,
  AI: (props: IconProps) => <Sparkles {...props} />,
  Home: (props: IconProps) => <Home {...props} />,
  Price: (props: IconProps) => <DollarSign {...props} />,
  Users: (props: IconProps) => <Users {...props} />,
  ExternalLink: (props: IconProps) => <ExternalLink {...props} />,
  Upload: (props: IconProps) => <Upload {...props} />,
  ShoppingCart: (props: IconProps) => <ShoppingCart {...props} />,
  Plus: (props: IconProps) => <Plus {...props} />,
  Minus: (props: IconProps) => <Minus {...props} />,
  X: (props: IconProps) => <X {...props} />,
  Link: (props: IconProps) => <Link {...props} />,
  Check: (props: IconProps) => <Check {...props} />,
  BookOpen: (props: IconProps) => <BookOpen {...props} />,
  CreditCard: (props: IconProps) => <CreditCard {...props} />,
  Orders: (props: IconProps) => <ShoppingBasket {...props} />,
  Spinner: (props: IconProps) => <Loader2 {...props} />,
  Store: (props: IconProps) => <Store {...props} />,
  Printer: (props: IconProps) => <Printer {...props} />,
  Whatsapp: (props: IconProps) => <MessageSquare {...props} />,
  SMS: (props: IconProps) => <Smartphone {...props} />,
  ScanLine: (props: IconProps) => <ScanLine {...props} />,
  Warehouse: (props: IconProps) => <Warehouse {...props} />,
  Receipt: (props: IconProps) => <Receipt {...props} />,
  Smile: (props: IconProps) => <Smile {...props} />,
  GitMerge: (props: IconProps) => <GitMerge {...props} />,
  Cloud: (props: IconProps) => <Cloud {...props} />,
  Cog: (props: IconProps) => <Cog {...props} />,
  Star: (props: IconProps) => <Star {...props} />,
};